apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  labels:
    cluster.x-k8s.io/provider: infrastructure-aws
  name: capa-serving-cert
  namespace: capi-webhook-system
spec:
  dnsNames:
  - capa-webhook-service.capi-webhook-system.svc
  - capa-webhook-service.capi-webhook-system.svc.cluster.local
  isCA: false
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: tmaxcloud-issuer
  secretName: capa-webhook-service-cert
  usages:
  - digital signature
  - key encipherment
  - server auth
  - client auth
