apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  labels:
    cluster.x-k8s.io/provider: cluster-api
  name: capi-serving-cert
  namespace: capi-webhook-system
spec:
  dnsNames:
  - capi-webhook-service.capi-webhook-system.svc
  - capi-webhook-service.capi-webhook-system.svc.cluster.local
  isCA: false
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: tmaxcloud-issuer
  secretName: capi-webhook-service-cert
  usages:
  - digital signature
  - key encipherment
  - server auth
  - client auth
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  labels:
    cluster.x-k8s.io/provider: bootstrap-kubeadm
  name: capi-kubeadm-bootstrap-serving-cert
  namespace: capi-webhook-system
spec:
  dnsNames:
  - capi-kubeadm-bootstrap-webhook-service.capi-webhook-system.svc
  - capi-kubeadm-bootstrap-webhook-service.capi-webhook-system.svc.cluster.local
  isCA: false
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: tmaxcloud-issuer
  secretName: capi-kubeadm-bootstrap-webhook-service-cert
  usages:
  - digital signature
  - key encipherment
  - server auth
  - client auth
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  labels:
    cluster.x-k8s.io/provider: control-plane-kubeadm
  name: capi-kubeadm-control-plane-serving-cert
  namespace: capi-webhook-system
spec:
  dnsNames:
  - capi-kubeadm-control-plane-webhook-service.capi-webhook-system.svc
  - capi-kubeadm-control-plane-webhook-service.capi-webhook-system.svc.cluster.local
  isCA: false
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: tmaxcloud-issuer
  secretName: capi-kubeadm-control-plane-webhook-service-cert
  usages:
  - digital signature
  - key encipherment
  - server auth
  - client auth
